### ISSUE TITLE
Multiple commands to get data

### ISSUE THREAD

**Issue by tpluscode** [ad-freiburg/qlever-control#118]
Similarly to how `MULTIPLE_INPUT_JSON` allows multiple command to pipe data to index, it would be useful to define multiple command to get data from various sources.

Re #117, YAML would make it much simpler with native support for arrays

```yaml
data:
  cmd:
    - curl ... -o fetched-file.nq # from web
    - mc cp bucket/foobar.gz ./foobar.gz # from S3
    - sparql ... > results.ttl # result of a query
```
